// <auto-generated />
using GameShop.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameShop.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220717220401_PicturesFix")]
    partial class PicturesFix
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("GameShop.Shared.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "MMORPG",
                            Url = "mmorpg"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Action",
                            Url = "action"
                        },
                        new
                        {
                            Id = 3,
                            Name = "FPS",
                            Url = "fps"
                        });
                });

            modelBuilder.Entity("GameShop.Shared.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Online MMORPG Game",
                            ImageUrl = "https://cdn.gracza.pl/galeria/gry13/grupy/731999812.jpg",
                            Price = 69.99m,
                            Title = "World of Warcraft: Dragonflight"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Description = "Action Game",
                            ImageUrl = "https://cdn1.epicgames.com/offer/9c59efaabb6a48f19b3485d5d9416032/EGS_LEGOStarWarsTheSkywalkerSaga_TTGames_S2_1200x1600-fba27b1ae598e355c3ad42d04d9025ba",
                            Price = 50m,
                            Title = "LEGO Star Wars Skywalker Saga"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Description = "FPS Game",
                            ImageUrl = "https://image.api.playstation.com/vulcan/img/rnd/202008/1900/lTSvbByTYMqy6R22teoybKCg.png",
                            Price = 90m,
                            Title = "Call of Duty World War"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "MMORPG Star Wars Game",
                            ImageUrl = "https://upload.wikimedia.org/wikipedia/en/3/3c/Star_Wars-_The_Old_Republic_cover.jpg",
                            Price = 30m,
                            Title = "Star Wars The Old Republic"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Description = "Action Game",
                            ImageUrl = "https://store.ubi.com/dw/image/v2/ABBS_PRD/on/demandware.static/-/Sites-masterCatalog/default/dwa8b6d5b5/images/large/56c4948888a7e300458b47da.jpg?sw=341&sh=450&sm=fit",
                            Price = 90m,
                            Title = "Rayman Legends"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Description = "FPS Online Game",
                            ImageUrl = "https://static-cdn.jtvnw.net/ttv-boxart/32399_IGDB-272x380.jpg",
                            Price = 10m,
                            Title = "Counter Strike"
                        });
                });

            modelBuilder.Entity("GameShop.Shared.Product", b =>
                {
                    b.HasOne("GameShop.Shared.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
